In [2]:
!pip install neattext

Collecting neattext
  Downloading neattext-0.1.2-py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 5.6 MB/s
Installing collected packages: neattext
Successfully installed neattext-0.1.2

In [72]:
import pandas as pd
import numpy as np
import neattext as nf
import re

In [73]:
ams = pd.read_csv('/content/drive/MyDrive/T5_Camp/animes.csv')

In [74]:
delete_genres = ['hentai', 'harem', 'yaoi', 'Yuri', 'ecchi', 'twincest', 'incest', 'lemon', 'smut']

In [75]:
ams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19311 entries, 0 to 19310
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         19311 non-null  int64
 1   title       19311 non-null  object
 2   synopsis    18336 non-null  object
 3   genre       19311 non-null  object
 4   aired       19311 non-null  object
 5   episodes    18605 non-null  float64
 6   members     19311 non-null  int64
 7   popularity  19311 non-null  int64
 8   ranked      16099 non-null  float64
 9   score       18732 non-null  float64
 10  img_url     19131 non-null  object
 11  link        19311 non-null  object
dtypes: float64(3), int64(3), object(6)
memory usage: 1.8+ MB

In [76]:
def clean_animes(animes):
  animes['score'] = animes['score'].astype(str)

  animes['synopsis'].fillna('None', inplace=True)
  animes['genre'].fillna('None', inplace=True)
  animes['episodes'].fillna(0, inplace=True)
  animes['score'].fillna('-', inplace=True)
  animes['img_url'].fillna('https://i.postimg.cc/fL9WXt0H/Capture.png', inplace=True)

  animes['episodes'] = animes['episodes'].astype(int)
  return animes

ams = clean_animes(ams)
ams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19311 entries, 0 to 19310
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         19311 non-null  int64
 1   title       19311 non-null  object
 2   synopsis    19311 non-null  object
 3   genre       19311 non-null  object
 4   aired       19311 non-null  object
 5   episodes    19311 non-null  int64
 6   members     19311 non-null  int64
 7   popularity  19311 non-null  int64
 8   ranked      16099 non-null  float64
 9   score       19311 non-null  object
 10  img_url     19311 non-null  object
 11  link        19311 non-null  object
dtypes: float64(1), int64(4), object(7)
memory usage: 1.8+ MB

In [77]:
ams

         uid  ...                                               link
0      28891  ...  https://myanimelist.net/anime/28891/Haikyuu_Se...
1      23273  ...  https://myanimelist.net/anime/23273/Shigatsu_w...
2      34599  ...  https://myanimelist.net/anime/34599/Made_in_Abyss
3       5114  ...  https://myanimelist.net/anime/5114/Fullmetal_A...
4      31758  ...  https://myanimelist.net/anime/31758/Kizumonoga...
...      ...  ...                                                ...
19306  32979  ...  https://myanimelist.net/anime/32979/Flip_Flappers
19307    123  ...    https://myanimelist.net/anime/123/Fushigi_Yuugi
19308   1281  ...  https://myanimelist.net/anime/1281/Gakkou_no_K...
19309    450  ...  https://myanimelist.net/anime/450/InuYasha_Mov...
19310     87  ...  https://myanimelist.net/anime/87/Mobile_Suit_G...

[19311 rows x 12 columns]

In [78]:
# delete unnecessary genre
def ignore_genre(genre):
  genre_mask = ams['genre'].str.contains(genre, case=False) == False
  return ams[genre_mask]


for gen in delete_genres:
  ams = ignore_genre(gen)

ams

         uid  ...                                               link
0      28891  ...  https://myanimelist.net/anime/28891/Haikyuu_Se...
1      23273  ...  https://myanimelist.net/anime/23273/Shigatsu_w...
2      34599  ...  https://myanimelist.net/anime/34599/Made_in_Abyss
3       5114  ...  https://myanimelist.net/anime/5114/Fullmetal_A...
4      31758  ...  https://myanimelist.net/anime/31758/Kizumonoga...
...      ...  ...                                                ...
19306  32979  ...  https://myanimelist.net/anime/32979/Flip_Flappers
19307    123  ...    https://myanimelist.net/anime/123/Fushigi_Yuugi
19308   1281  ...  https://myanimelist.net/anime/1281/Gakkou_no_K...
19309    450  ...  https://myanimelist.net/anime/450/InuYasha_Mov...
19310     87  ...  https://myanimelist.net/anime/87/Mobile_Suit_G...

[15694 rows x 12 columns]

In [79]:
def extract_years(text):
    years = []

    pattern = re.compile('\d{4}')
    matches = pattern.finditer(text)
    for match in matches:
        years.append(match.group(0))

    return years

def extract_dates(anime_df):
    years = anime_df['aired'].apply(lambda x: extract_years(x))
    anime_df['release_date'] = [e[0] if e else -1 for e in years]

    end_dates = []
    for e in years:
        try:
            end_dates.append(e[1])
        except:
            end_dates.append(-1)

    anime_df['end_date'] = end_dates
    return anime_df


ams = extract_dates(ams)
ams

         uid                                        title  ... release_date end_date
0      28891                      Haikyuu!! Second Season  ...         2015     2016
1      23273                      Shigatsu wa Kimi no Uso  ...         2014     2015
2      34599                                Made in Abyss  ...         2017     2017
3       5114             Fullmetal Alchemist: Brotherhood  ...         2009     2010
4      31758             Kizumonogatari III: Reiketsu-hen  ...         2017       -1
...      ...                                          ...  ...          ...      ...
19306  32979                                Flip Flappers  ...         2016     2016
19307    123                                Fushigi Yuugi  ...         1995     1996
19308   1281                             Gakkou no Kaidan  ...         2000     2001
19309    450  InuYasha Movie 2: Kagami no Naka no Mugenjo  ...         2002       -1
19310     87     Mobile Suit Gundam: Char's Counterattack  ...         1988       -1

[15694 rows x 14 columns]

In [80]:
ams['release_date'] = ams['release_date'].astype(int)
ams['end_date'] = ams['end_date'].astype(int)
ams.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15694 entries, 0 to 19310
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   uid           15694 non-null  int64
 1   title         15694 non-null  object
 2   synopsis      15694 non-null  object
 3   genre         15694 non-null  object
 4   aired         15694 non-null  object
 5   episodes      15694 non-null  int64
 6   members       15694 non-null  int64
 7   popularity    15694 non-null  int64
 8   ranked        15160 non-null  float64
 9   score         15694 non-null  object
 10  img_url       15694 non-null  object
 11  link          15694 non-null  object
 12  release_date  15694 non-null  int64
 13  end_date      15694 non-null  int64
dtypes: float64(1), int64(6), object(7)
memory usage: 1.8+ MB

In [81]:
ams

         uid  ... end_date
0      28891  ...     2016
1      23273  ...     2015
2      34599  ...     2017
3       5114  ...     2010
4      31758  ...       -1
...      ...  ...      ...
19306  32979  ...     2016
19307    123  ...     1996
19308   1281  ...     2001
19309    450  ...       -1
19310     87  ...       -1

[15694 rows x 14 columns]

In [82]:
ams['genre'] = ams['genre'].apply(lambda x: nf.remove_special_characters(x).replace(' ', ', '))
ams

         uid  ... end_date
0      28891  ...     2016
1      23273  ...     2015
2      34599  ...     2017
3       5114  ...     2010
4      31758  ...       -1
...      ...  ...      ...
19306  32979  ...     2016
19307    123  ...     1996
19308   1281  ...     2001
19309    450  ...       -1
19310     87  ...       -1

[15694 rows x 14 columns]

In [83]:
syn = ams['synopsis']
syn

0        Following their participation at the Inter-Hig...
1        Music accompanies the path of the human metron...
2        The Abyss—a gaping chasm stretching down into ...
3        "In order for something to be obtained, someth...
4        After helping revive the legendary vampire Kis...
                               ...
19306    Cocona is an average middle schooler living wi...
19307    While visiting the National Library, junior-hi...
19308    Years ago, all of the ghosts in a haunted scho...
19309    Inuyasha and company have finally destroyed Na...
19310    The year is Universal Century 0093. Char Aznab...
Name: synopsis, Length: 15694, dtype: object

In [84]:
syn = syn.astype('str')
syn = syn.apply(nf.remove_multiple_spaces)
syn = syn.apply(nf.remove_special_characters)
ams['synopsis'] = syn
ams

         uid  ... end_date
0      28891  ...     2016
1      23273  ...     2015
2      34599  ...     2017
3       5114  ...     2010
4      31758  ...       -1
...      ...  ...      ...
19306  32979  ...     2016
19307    123  ...     1996
19308   1281  ...     2001
19309    450  ...       -1
19310     87  ...       -1

[15694 rows x 14 columns]

In [85]:
ams.drop(columns=['aired', 'members', 'popularity', 'ranked', 'link'], inplace=True)
ams

         uid  ... end_date
0      28891  ...     2016
1      23273  ...     2015
2      34599  ...     2017
3       5114  ...     2010
4      31758  ...       -1
...      ...  ...      ...
19306  32979  ...     2016
19307    123  ...     1996
19308   1281  ...     2001
19309    450  ...       -1
19310     87  ...       -1

[15694 rows x 9 columns]

In [86]:
ams.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15694 entries, 0 to 19310
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   uid           15694 non-null  int64
 1   title         15694 non-null  object
 2   synopsis      15694 non-null  object
 3   genre         15694 non-null  object
 4   episodes      15694 non-null  int64
 5   score         15694 non-null  object
 6   img_url       15694 non-null  object
 7   release_date  15694 non-null  int64
 8   end_date      15694 non-null  int64
dtypes: int64(4), object(5)
memory usage: 1.2+ MB

# Save Filtered Animes in CSV File for Deployment

In [87]:
ams.to_csv('/content/drive/MyDrive/T5_Camp/filtered_animes.csv', index=False)

---